# Generated by Django 3.2 on 2023-01-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230112_2127'),
        ('reviews', '0002_auto_20230113_1545'),
    ]

    operations = [
    ]
